name: chicago_crime_dbt
version: 1.0.0
config-version: 2

profile: chicago_crime_dbt

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]

models:
  chicago_crime_dbt:
    +materialized: view

    staging:
      +materialized: view

    dimensions:
      +materialized: view

    facts:
      +materialized: table

    marts:
      +materialized: table