name: 'chicago_crime_dbt'
version: '1.0.0'
config-version: 2
profile: chicago_crime_dbt
model-paths: ['models']
seed-paths: ['seeds']

models:
  chicago_crime_dbt:
    +materialized: view
    staging:
      +schema: stg
    dimensions:
      +schema: core
    facts:
      +schema: core
    marts:
      +schema: marts
